// This file has been generated by Specta. DO NOT EDIT.

export type PlayerLapTimes = PlayerLapTimesData[]

export type DeltaLastTime = string

export type PlayerLapTimesData = { lap: number; lap_time: string }

export type RelativeDriver = { car_id: number; position: number; user_name: string; car_number: string; irating: string; license: string; player_relative_gap: string; is_player: boolean; is_in_pits: boolean; is_off_track: boolean; is_off_world: boolean }

export type Standings = StandingsDriver[]

export type StrengthOfField = number

export type SubTimerWidgetSettings = { enabled: boolean; x: number; y: number; session_state_width: number; gap_enabled: boolean; gap_width: number; opacity: number }

export type StandingsDriver = { car_id: number; position: number; user_name: string; car_number: string; irating: string; license: string; leader_gap: string; best_lap: string; last_lap: string; is_player: boolean; is_leader: boolean; is_in_pits: boolean; split_after: boolean }

export type GearBlinkRpm = number

export type ProximityWidgetSettings = { enabled: boolean; x: number; y: number; gap_width: number }

export type DeltaBestTime = string

export type TelemetryGraph = { ts: number; throttle: number; brake: number; abs_active: boolean }

export type Speed = number

export type LapTimesWidgetSettings = { enabled: boolean; x: number; y: number; width: number; opacity: number }

export type GearShiftRpm = number

export type RelativeWidgetSettings = { enabled: boolean; x: number; y: number; width: number; opacity: number }

export type TrackMapWidgetSettings = { enabled: boolean; x: number; y: number; width: number; opacity: number }

export type MainWidgetSettings = { enabled: boolean; x: number; y: number; width: number; opacity: number }

export type Lap = number

export type LapsTotal = number

export type Active = boolean

export type TrackId = number

export type TimerWidgetSettings = { enabled: boolean; x: number; y: number; lap_time_width: number; delta_enabled: boolean; delta_width: number; opacity: number }

export type PositionsTotal = number

export type Rpm = number

export type CurrentTime = string

export type SessionState = string

export type Relative = RelativeDriver[]

export type TelemetryWidgetSettings = { enabled: boolean; x: number; y: number; width: number; opacity: number; show_reference_telemetry: boolean | null }

export type RaceLaps = number

export type Gear = string

export type TrackMapDriver = { car_id: number; position: number; is_leader: boolean; is_player: boolean; lap_dist_pct: number; is_in_pits: boolean; is_off_track: boolean; is_off_world: boolean }

export type SessionTime = string

export type GapNext = string

export type IncidentLimit = number

export type StandingsWidgetSettings = { enabled: boolean; x: number; y: number; width: number; opacity: number; max_drivers: number; top_drivers: number }

export type Incidents = number

export type LapTime = number

export type Position = number

export type Proximity = { is_left: boolean; is_right: boolean }

export type GapPrev = string

export type SessionTimeTotal = string

export type TrackMap = TrackMapDriver[]

